version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql
    environment:
      MYSQL_DATABASE: counter
      # You should definitely change the password in production
      MYSQL_PASSWORD: 
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    restart: always
    volumes:
      - db-data:/var/lib/mysql
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
  logcounter:
    build: .
    ports:
      - 8000:80
  
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/logcounter
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - logcounter
      - database

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
